### ISSUE TITLE
Anyone can Deob this

### ISSUE THREAD

**Issue by w4nts** [TheAxes/AxeSelfbot#13]
I recommend using PyArmor I de obbed it and didn’t see any loggers or anything so I deem this safe for any user :) also thanks for being legit and not logging

**Comment by TheAxes** [comment]
TheAxes are always legit and i know that base64 is a shitty obfuscation.
Thanks for your suggestion btw.

**Comment by w4nts** [comment]
No problem add me on discord Mali#0001

**Comment by TheAxes** [comment]
Alright!
