### ISSUE TITLE
I found a problem in selfnuker v1

### ISSUE THREAD

**Issue by Swagat8** [TheAxes/AxeSelfbot#16]
![Screenshot_2023-06-08-19-35-25-567_com android chrome](https://github.com/TheAxes/AxeSelfbot/assets/133507180/56b64590-eba2-471c-b7e6-88e302cbedd0)

**Comment by TheAxes** [comment]
Ask me on discord, also it's your mistake re-watch the tutorial.

Its not error with the script.
