### ISSUE TITLE
Easy Deobfuscation lol

### ISSUE THREAD

**Issue by Pr0t0ns** [TheAxes/AxeSelfbot#2]
It's a better idea to just compile the src code with like nuitka instead of obfuscating your src with whatever shitty obfuscation thing you used, because i got the src in about 2 minutes without even trying, if you know basic python you would be able to see how i deobfuscated the src. (https://easyupload.io/gdtz0i) <-- most of it is readable, if you want to make it completely plain text all you would have to do is decode the bytes using utf-8 encoding.

**Comment by Pr0t0ns** [comment]
One thing i want to add is i appreciate you not trying to hide anything weird in the source code most people who obfuscate or compile their code usually have some weird things inside the src xd

**Comment by TheAxes** [comment]
Thanks For Suggestion!
i try it next time but for now pls delete the src :p
it don't have any shitty logger if u read it ;-;

**Comment by TheAxes** [comment]
._.
