### ISSUE TITLE
I don't know what I have to do with env. Please any advice..

### ISSUE THREAD

**Issue by 0Zombie** [TheAxes/AxeSelfbot#4]

**Comment by zfzd** [comment]
g i

**Comment by TheAxes** [comment]
just put key name to token and value as you account token then run it.

**Comment by zfzd** [comment]
yes but when I open the .py file the program just closes...

**Comment by TheAxes** [comment]
use an terminal to run the file

**Comment by zfzd** [comment]
how do I do that?

**Comment by TheAxes** [comment]
use command prompt or replit.

**Comment by 0Zombie** [comment]
yes but my question is what is the command for that

**Comment by 0Zombie** [comment]
that it runs the file in cmd, I know how to open a prompt but I don't know the command for it that it runs the .py file

**Comment by TheAxes** [comment]
> that it runs the file in cmd, I know how to open a prompt but I don't know the command for it that it runs the .py file

https://www.wikihow.com/Use-Windows-Command-Prompt-to-Run-a-Python-File?amp=1#aoh=16648739169992&referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s 
This Article may help You.
