### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by 0Zombie** [TheAxes/AxeSelfbot#5]
Hey, it's me again and I'm getting this error. Any ideas how to fix it?

_File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\AxeSelfbot-main\main.py", line 142
    initial = random.randrange(0, 60)
IndentationError: unexpected indent_

**Thanks for reading.**

**Comment by TheAxes** [comment]
did you tried to edit the code? because it have no indentation errors.

**Comment by 0Zombie** [comment]
Ehm no.. I didn't do anything. I just downloaded and ran pip install -r requirements.txt in a cmd prompt and after that I just ran the .py file.. that are the only things I did..

**Comment by TheAxes** [comment]
clone it again and test it
