### ISSUE TITLE
bro :skull: 

### ISSUE THREAD

**Issue by nostorian** [TheAxes/AxeSelfbot#6]
why would you encrypt the code with base64, that's like the worst encryption ever, i could easily decode the entire program within a minute, use nuitka or [this obfuscator](https://github.com/billythegoat356/Hyperion), base64 encoding is trash af and anyone could steal the code easily

**Comment by TheAxes** [comment]
suggest me a good obfuscation then :\

**Comment by TheAxes** [comment]
thanks for suggestions!
